query plant($id: ID!, $lang: String) {
  plant(id: $id) {
    id
    name
    species
    description
    imageUrl
    wateringIntervalSummerDays
    wateringIntervalWinterDays
    lastWateredOn
    nextDueOn
    speciesInfo(lang: $lang) {
      description
      origin
    }
    careSheet(lang: $lang) {
      light
      humidity
      tip
    }
    wateringHistory {
      id
      wateredOn
    }
  }
}
