import { Injectable } from '@nestjs/common';
import { CareDueService } from '../plantCare/due.service';
import { CareType } from '../plantCare/enum';
import { CareRepository } from '../plantCare/repository';
import { WateringRepository } from '../watering/repository';
import { WateringScheduleService } from '../watering/schedule.service';
import { buildIcsFeed, FeedEvent } from './ics-builder';

type Locale = 'fr' | 'en';

const normalise = (locale: string): Locale =>
  locale.toLowerCase().startsWith('en') ? 'en' : 'fr';

const CARE_LABEL: Record<Locale, Record<CareType, string>> = {
  fr: {
    [CareType.FERTILIZING]: 'engrais',
    [CareType.MISTING]: 'brumisation',
    [CareType.ROTATING]: 'rotation vers la lumière',
    [CareType.REPOTTING]: 'rempotage',
  },
  en: {
    [CareType.FERTILIZING]: 'fertilising',
    [CareType.MISTING]: 'misting',
    [CareType.ROTATING]: 'rotate toward the light',
    [CareType.REPOTTING]: 'repotting',
  },
};

const COPY = {
  fr: {
    wateringTitle: (name: string): string => `Arroser ${name}`,
    wateringDescription: (name: string): string =>
      `Rappel d'arrosage pour ${name}, généré par verdure.`,
    careTitle: (name: string, task: string): string => `${name} : ${task}`,
    careDescription: (name: string, task: string): string =>
      `Rappel « ${task} » pour ${name}, généré par verdure.`,
  },
  en: {
    wateringTitle: (name: string): string => `Water ${name}`,
    wateringDescription: (name: string): string =>
      `Watering reminder for ${name}, generated by verdure.`,
    careTitle: (name: string, task: string): string => `${name}: ${task}`,
    careDescription: (name: string, task: string): string =>
      `"${task}" reminder for ${name}, generated by verdure.`,
  },
};

// Aggregates every plant's watering + care schedules into one live ICS feed:
// one non-recurring event per due task, recomputed fresh on each fetch.
@Injectable()
export class CalendarFeedService {
  constructor(
    private readonly watering: WateringRepository,
    private readonly wateringSchedule: WateringScheduleService,
    private readonly care: CareRepository,
    private readonly careDue: CareDueService,
  ) {}

  async icsFor(userId: string, locale: string): Promise<string> {
    const [wateringRecords, careRecords] = await Promise.all([
      this.watering.wateringRecordsFor(userId),
      this.care.careRecordsFor(userId),
    ]);

    const copy = COPY[normalise(locale)];
    const careLabel = CARE_LABEL[normalise(locale)];

    const wateringEvents = wateringRecords
      .map((record): FeedEvent | undefined => {
        const dueOn = this.wateringSchedule.nextDue(
          record.lastWateredOn,
          record.summerDays,
          record.winterDays,
        );
        return dueOn === null
          ? undefined
          : {
              uid: `watering-${record.id}`,
              title: copy.wateringTitle(record.name),
              description: copy.wateringDescription(record.name),
              dueOn,
            };
      })
      .filter((event): event is FeedEvent => event !== undefined);

    const careEvents = careRecords
      .map((record): FeedEvent | undefined => {
        const dueOn = this.careDue.nextDueOn(
          record.lastDoneOn,
          record.intervalDays,
        );
        const task = careLabel[record.careType];
        return dueOn === null
          ? undefined
          : {
              uid: `care-${record.plantId}-${record.careType}`,
              title: copy.careTitle(record.plantName, task),
              description: copy.careDescription(record.plantName, task),
              dueOn,
            };
      })
      .filter((event): event is FeedEvent => event !== undefined);

    return buildIcsFeed([...wateringEvents, ...careEvents]);
  }
}
